//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoPersonas
    {
        public System.Guid CargoPersonaId { get; set; }
        public System.Guid CargoId { get; set; }
        public System.Guid PersonaId { get; set; }
        public System.Guid DepartamentoId { get; set; }
        public System.Guid JornadaId { get; set; }
        public System.DateTime Actualizacion { get; set; }
    
        public virtual Jornadas Jornadas { get; set; }
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
