//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlDeAsistenciaEntities : DbContext
    {
        public ControlDeAsistenciaEntities()
            : base("name=ControlDeAsistenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencias> Asistencias { get; set; }
        public virtual DbSet<ControlPersonal> ControlPersonal { get; set; }
        public virtual DbSet<Jornadas> Jornadas { get; set; }
        public virtual DbSet<Justificaciones> Justificaciones { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Sanciones> Sanciones { get; set; }
        public virtual DbSet<Vacaciones> Vacaciones { get; set; }
        public virtual DbSet<CargoPersonas> CargoPersonas { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Correos> Correos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
        public virtual DbSet<Ubigeos> Ubigeos { get; set; }
        public virtual DbSet<Entidades> Entidades { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<ReporteModulos> ReporteModulos { get; set; }
        public virtual DbSet<Reportes> Reportes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolUsuarios> RolUsuarios { get; set; }
        public virtual DbSet<Sesiones> Sesiones { get; set; }
        public virtual DbSet<UsuarioEquipo> UsuarioEquipo { get; set; }
        public virtual DbSet<UsuarioModulos> UsuarioModulos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Auditorias> Auditorias { get; set; }
    }
}
