//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public System.Guid SesionId { get; set; }
        public System.Guid UsuarioEquipoId { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Final { get; set; }
        public bool Habilitado { get; set; }
        public int TipoEntrada { get; set; }
        public System.DateTime Actualizacion { get; set; }
    
        public virtual UsuarioEquipo UsuarioEquipo { get; set; }
    }
}
