//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioModulos
    {
        public System.Guid UsuarioModuloId { get; set; }
        public System.Guid UsuarioId { get; set; }
        public System.Guid ModuloId { get; set; }
        public System.DateTime Actualizacion { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
