//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEscritorio.PersonaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPersona", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class EPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AcutalizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EAsistencia[] AsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.ECargoPersona[] CargoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EControlPersonal[] ControlPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.ECorreo[] CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EDireccion[] DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EJustificacion[] JustificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreGeneradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPermiso[] PermisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.ESanciones[] SancionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.ETelefono[] TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoSexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EVacaciones[] VacacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Acutalizacion {
            get {
                return this.AcutalizacionField;
            }
            set {
                if ((this.AcutalizacionField.Equals(value) != true)) {
                    this.AcutalizacionField = value;
                    this.RaisePropertyChanged("Acutalizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EAsistencia[] Asistencia {
            get {
                return this.AsistenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.AsistenciaField, value) != true)) {
                    this.AsistenciaField = value;
                    this.RaisePropertyChanged("Asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.ECargoPersona[] CargoPersona {
            get {
                return this.CargoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoPersonaField, value) != true)) {
                    this.CargoPersonaField = value;
                    this.RaisePropertyChanged("CargoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EControlPersonal[] ControlPersonal {
            get {
                return this.ControlPersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlPersonalField, value) != true)) {
                    this.ControlPersonalField = value;
                    this.RaisePropertyChanged("ControlPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.ECorreo[] Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EDireccion[] Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EJustificacion[] Justificacion {
            get {
                return this.JustificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.JustificacionField, value) != true)) {
                    this.JustificacionField = value;
                    this.RaisePropertyChanged("Justificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Nacimiento {
            get {
                return this.NacimientoField;
            }
            set {
                if ((this.NacimientoField.Equals(value) != true)) {
                    this.NacimientoField = value;
                    this.RaisePropertyChanged("Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreGenerado {
            get {
                return this.NombreGeneradoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreGeneradoField, value) != true)) {
                    this.NombreGeneradoField = value;
                    this.RaisePropertyChanged("NombreGenerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPermiso[] Permiso {
            get {
                return this.PermisoField;
            }
            set {
                if ((object.ReferenceEquals(this.PermisoField, value) != true)) {
                    this.PermisoField = value;
                    this.RaisePropertyChanged("Permiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.ESanciones[] Sanciones {
            get {
                return this.SancionesField;
            }
            set {
                if ((object.ReferenceEquals(this.SancionesField, value) != true)) {
                    this.SancionesField = value;
                    this.RaisePropertyChanged("Sanciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.ETelefono[] Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoSexo {
            get {
                return this.TipoSexoField;
            }
            set {
                if ((this.TipoSexoField.Equals(value) != true)) {
                    this.TipoSexoField = value;
                    this.RaisePropertyChanged("TipoSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EVacaciones[] Vacaciones {
            get {
                return this.VacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.VacacionesField, value) != true)) {
                    this.VacacionesField = value;
                    this.RaisePropertyChanged("Vacaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EAsistencia", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Asistencia")]
    [System.SerializableAttribute()]
    public partial class EAsistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinalAlmuerzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InicioAlmuerzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SalidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FinalAlmuerzo {
            get {
                return this.FinalAlmuerzoField;
            }
            set {
                if ((this.FinalAlmuerzoField.Equals(value) != true)) {
                    this.FinalAlmuerzoField = value;
                    this.RaisePropertyChanged("FinalAlmuerzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ingreso {
            get {
                return this.IngresoField;
            }
            set {
                if ((this.IngresoField.Equals(value) != true)) {
                    this.IngresoField = value;
                    this.RaisePropertyChanged("Ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InicioAlmuerzo {
            get {
                return this.InicioAlmuerzoField;
            }
            set {
                if ((this.InicioAlmuerzoField.Equals(value) != true)) {
                    this.InicioAlmuerzoField = value;
                    this.RaisePropertyChanged("InicioAlmuerzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Mes {
            get {
                return this.MesField;
            }
            set {
                if ((this.MesField.Equals(value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Salida {
            get {
                return this.SalidaField;
            }
            set {
                if ((this.SalidaField.Equals(value) != true)) {
                    this.SalidaField = value;
                    this.RaisePropertyChanged("Salida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECargoPersona", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class ECargoPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.ECargo CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CargoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EDepartamento DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EJornada JornadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid JornadaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.ECargo Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CargoId {
            get {
                return this.CargoIdField;
            }
            set {
                if ((this.CargoIdField.Equals(value) != true)) {
                    this.CargoIdField = value;
                    this.RaisePropertyChanged("CargoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EDepartamento Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((this.DepartamentoIdField.Equals(value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EJornada Jornada {
            get {
                return this.JornadaField;
            }
            set {
                if ((object.ReferenceEquals(this.JornadaField, value) != true)) {
                    this.JornadaField = value;
                    this.RaisePropertyChanged("Jornada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid JornadaId {
            get {
                return this.JornadaIdField;
            }
            set {
                if ((this.JornadaIdField.Equals(value) != true)) {
                    this.JornadaIdField = value;
                    this.RaisePropertyChanged("JornadaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EControlPersonal", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Asistencia")]
    [System.SerializableAttribute()]
    public partial class EControlPersonal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasAsistidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasFaltadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Desde {
            get {
                return this.DesdeField;
            }
            set {
                if ((this.DesdeField.Equals(value) != true)) {
                    this.DesdeField = value;
                    this.RaisePropertyChanged("Desde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasAsistidos {
            get {
                return this.DiasAsistidosField;
            }
            set {
                if ((this.DiasAsistidosField.Equals(value) != true)) {
                    this.DiasAsistidosField = value;
                    this.RaisePropertyChanged("DiasAsistidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasFaltados {
            get {
                return this.DiasFaltadosField;
            }
            set {
                if ((this.DiasFaltadosField.Equals(value) != true)) {
                    this.DiasFaltadosField = value;
                    this.RaisePropertyChanged("DiasFaltados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hasta {
            get {
                return this.HastaField;
            }
            set {
                if ((this.HastaField.Equals(value) != true)) {
                    this.HastaField = value;
                    this.RaisePropertyChanged("Hasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECorreo", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class ECorreo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDireccion", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class EDireccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.DireccionTipo TipoDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EUbigeo UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UbigeoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrbanizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreVia {
            get {
                return this.NombreViaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreViaField, value) != true)) {
                    this.NombreViaField = value;
                    this.RaisePropertyChanged("NombreVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.DireccionTipo TipoDireccion {
            get {
                return this.TipoDireccionField;
            }
            set {
                if ((this.TipoDireccionField.Equals(value) != true)) {
                    this.TipoDireccionField = value;
                    this.RaisePropertyChanged("TipoDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EUbigeo Ubigeo {
            get {
                return this.UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoField, value) != true)) {
                    this.UbigeoField = value;
                    this.RaisePropertyChanged("Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UbigeoId {
            get {
                return this.UbigeoIdField;
            }
            set {
                if ((this.UbigeoIdField.Equals(value) != true)) {
                    this.UbigeoIdField = value;
                    this.RaisePropertyChanged("UbigeoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion {
            get {
                return this.UrbanizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UrbanizacionField, value) != true)) {
                    this.UrbanizacionField = value;
                    this.RaisePropertyChanged("Urbanizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EJustificacion", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Asistencia")]
    [System.SerializableAttribute()]
    public partial class EJustificacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPermiso", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Asistencia")]
    [System.SerializableAttribute()]
    public partial class EPermiso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESanciones", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Asistencia")]
    [System.SerializableAttribute()]
    public partial class ESanciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETelefono", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class ETelefono : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.TelefonoTipo TipoTelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroTelefono {
            get {
                return this.NroTelefonoField;
            }
            set {
                if ((this.NroTelefonoField.Equals(value) != true)) {
                    this.NroTelefonoField = value;
                    this.RaisePropertyChanged("NroTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.TelefonoTipo TipoTelefono {
            get {
                return this.TipoTelefonoField;
            }
            set {
                if ((this.TipoTelefonoField.Equals(value) != true)) {
                    this.TipoTelefonoField = value;
                    this.RaisePropertyChanged("TipoTelefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EVacaciones", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Asistencia")]
    [System.SerializableAttribute()]
    public partial class EVacaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Final {
            get {
                return this.FinalField;
            }
            set {
                if ((this.FinalField.Equals(value) != true)) {
                    this.FinalField = value;
                    this.RaisePropertyChanged("Final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((this.InicioField.Equals(value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECargo", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class ECargo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.ECargoPersona[] CargoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.ECargoPersona[] CargoPersona {
            get {
                return this.CargoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoPersonaField, value) != true)) {
                    this.CargoPersonaField = value;
                    this.RaisePropertyChanged("CargoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDepartamento", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class EDepartamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.ECargoPersona[] CargoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.ECargoPersona[] CargoPersona {
            get {
                return this.CargoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoPersonaField, value) != true)) {
                    this.CargoPersonaField = value;
                    this.RaisePropertyChanged("CargoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EJornada", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Asistencia")]
    [System.SerializableAttribute()]
    public partial class EJornada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoJornadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ingreso {
            get {
                return this.IngresoField;
            }
            set {
                if ((this.IngresoField.Equals(value) != true)) {
                    this.IngresoField = value;
                    this.RaisePropertyChanged("Ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Salida {
            get {
                return this.SalidaField;
            }
            set {
                if ((this.SalidaField.Equals(value) != true)) {
                    this.SalidaField = value;
                    this.RaisePropertyChanged("Salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoJornada {
            get {
                return this.TipoJornadaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoJornadaField, value) != true)) {
                    this.TipoJornadaField = value;
                    this.RaisePropertyChanged("TipoJornada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EUbigeo", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Comun")]
    [System.SerializableAttribute()]
    public partial class EUbigeo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteEscritorio.PersonaService.EDireccion[] DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Actualizacion {
            get {
                return this.ActualizacionField;
            }
            set {
                if ((this.ActualizacionField.Equals(value) != true)) {
                    this.ActualizacionField = value;
                    this.RaisePropertyChanged("Actualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteEscritorio.PersonaService.EDireccion[] Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionTipo", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Enumeradores")]
    public enum DireccionTipo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Calle = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jiron = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AAHH = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefonoTipo", Namespace="http://schemas.datacontract.org/2004/07/Entidad.Enumeradores")]
    public enum TelefonoTipo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Celular = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Casa = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonaService.ICPersona")]
    public interface ICPersona {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPersona/CrearCuenta", ReplyAction="http://tempuri.org/ICPersona/CrearCuentaResponse")]
        bool CrearCuenta(ClienteEscritorio.PersonaService.EPersona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPersona/CrearCuenta", ReplyAction="http://tempuri.org/ICPersona/CrearCuentaResponse")]
        System.Threading.Tasks.Task<bool> CrearCuentaAsync(ClienteEscritorio.PersonaService.EPersona persona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPersonaChannel : ClienteEscritorio.PersonaService.ICPersona, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPersonaClient : System.ServiceModel.ClientBase<ClienteEscritorio.PersonaService.ICPersona>, ClienteEscritorio.PersonaService.ICPersona {
        
        public CPersonaClient() {
        }
        
        public CPersonaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPersonaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPersonaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPersonaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CrearCuenta(ClienteEscritorio.PersonaService.EPersona persona) {
            return base.Channel.CrearCuenta(persona);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCuentaAsync(ClienteEscritorio.PersonaService.EPersona persona) {
            return base.Channel.CrearCuentaAsync(persona);
        }
    }
}
